export const CHANNEL_CREATE = 'CHANNEL_CREATE';
export const CHANNEL_RENAME = 'CHANNEL_RENAME';
export const CHANNEL_DELETE = 'CHANNEL_DELETE';

export const MESSAGE_CREATE = 'MESSAGE_CREATE';
export const MESSAGE_EDIT = 'MESSAGE_EDIT';
export const MESSAGE_DELETE = 'MESSAGE_DELETE';
export const MESSAGE_LIKE = 'MESSAGE_LIKE';
export const MESSAGE_DISLIKE = 'MESSAGE_DISLIKE';

export const USER_LOG_IN = 'USER_LOG_IN';
export const USER_LOG_OUT = 'USER_LOG_OUT';

export const USERNAME_CHANGES_SAVE = 'USERNAME_CHANGES_SAVE';
