export const CHANNEL_CREATE = 'CHANNEL_CREATE';
export const CHANNEL_RENAME = 'CHANNEL_RENAME';
export const CHANNEL_DELETE = 'CHANNEL_DELETE';

export const MESSAGE_CREATE = 'MESSAGE_CREATE';
export const MESSAGE_EDIT = 'MESSAGE_EDIT';
export const MESSAGE_DELETE = 'MESSAGE_DELETE';
export const MESSAGE_LIKE = 'MESSAGE_LIKE';
export const MESSAGE_DISLIKE = 'MESSAGE_DISLIKE';

export const STATUS_LOG_IN = 'STATUS_LOG_IN';
export const STATUS_LOG_OUT = 'STATUS_LOG_OUT';
