export const CHANNEL_CREATE = 'CHANNEL_CREATE';
export const CHANNEL_UPDATE = 'CHANNEL_UPDATE';
export const CHANNEL_DELETE = 'CHANNEL_DELETE';
export const CHANNEL_SELECT = 'CHANNEL_SELECT';

export const CHANNELS_FETCH__REQUEST = 'CHANNELS_FETCH__REQUEST';
export const CHANNELS_FETCH__SUCCESS = 'CHANNELS_FETCH__SUCCESS';
export const CHANNELS_FETCH__FAILURE = 'CHANNELS_FETCH__FAILURE';

export const MESSAGES_FETCH__REQUEST = 'MESSAGES_FETCH__REQUEST';
export const MESSAGES_FETCH__SUCCESS = 'MESSAGES_FETCH__SUCCESS';
export const MESSAGES_FETCH__FAILURE = 'MESSAGES_FETCH__FAILURE';
export const MESSAGES_DELETE__SUCCESS = 'MESSAGES_DELETE__SUCCESS';
export const MESSAGES_DELETE__FAILURE = 'MESSAGES_DELETE__FAILURE';
export const MESSAGES_POST__SUCCESS = 'MESSAGES_POST__SUCCESS';
export const MESSAGES_POST__FAILURE = 'MESSAGES_POST__FAILURE';
export const MESSAGES_UPDATE__SUCCESS = 'MESSAGES_UPDATE__SUCCESS';
export const MESSAGES_UPDATE__FAILURE = 'MESSAGES_UPDATE__FAILURE';

export const MESSAGE_CREATE = 'MESSAGE_CREATE';
export const MESSAGE_DELETE = 'MESSAGE_DELETE';
export const MESSAGE_LIKE = 'MESSAGE_LIKE';
export const MESSAGE_DISLIKE = 'MESSAGE_DISLIKE';


export const USER_LOG_IN = 'USER_LOG_IN';
export const USER_LOG_OUT = 'USER_LOG_OUT';
export const USER_CHANGE_AVATAR = 'USER_CHANGE_AVATAR';
export const USER_CHANGE_USERNAME = 'USER_CHANGE_USERNAME';
